### ISSUE TITLE
Error on watch page (self-hosted instance)

### ISSUE THREAD

**Issue by skgupta507** [codeblitz97/elyzen#12]
hey @codeblitz97 @avalynndev  i ran into an error on my self-hosted instance. the below error accours when i click at the episode i want to watch.  
this is the vercel log...............................................................................

TypeError: Cannot read properties of undefined (reading '0')
    at c (/var/task/.next/server/app/watch/[id]/page.js:1:178476)
    at eh (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:134786)
    at e (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:137671)
    at ek (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:138145)
    at eR (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142124)
    at eE (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:142698)
    at Timeout._onTimeout (/var/task/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:135475)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  digest: '1358491401'
}

![image](https://github.com/codeblitz97/elyzen/assets/131786207/c962c771-d2ed-485e-8357-0d06e461edf3)

kindly help me with this issue.

**Comment by skgupta507** [comment]
i ran into the same error when i tried to play ONE PIECE on the main website [original site].

**Comment by sulvii** [comment]
It's working smooth for me in the original site

**Comment by sulvii** [comment]
Add me on this discord id: sohom829

**Comment by skgupta507** [comment]
> It's working smooth for me in the original site

yes i checked once again on the main site and its working.

but on my deployed site iam still getting the error
https://elyzenx.vercel.app
site link.
